concept_maps = {
 '%': ('http://unitsofmeasure.org', '%', 'Percent'),
 '2 hours postprandial': ('http://www.fhir.org/guides/mfhir/CodeSystem/temporal-relationship-to-meal', '2-hours-postprandial', None),
 'AU': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'AU', None),
 'AU/mL': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'AU/mL', None),
 'BAU': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'BAU', None),
 'BAU/mL': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'BAU/mL', None),
 'BU': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'BU', None),
 'C': ('http://unitsofmeasure.org', 'Cel', 'degree Celsius'),
 'CCID_50': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'CCID_50', None),
 'Ci': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'Ci', None),
 'Cup': ('http://unitsofmeasure.org', '[cup_us]', 'cup'),
 "D'ag'U": ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', "D'ag'U", None),
 'F': ('http://unitsofmeasure.org', '[degF]', 'degree Fahrenheit'),
 'FFU': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'FFU', None),
 'Friday': ('http://snomed.info/sct', '307150005', 'Friday'),
 'IU': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'IU', None),
 'IU/L': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'IU/L', None),
 'IU/mL': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'IU/mL', None),
 'K': ('http://unitsofmeasure.org', 'K', 'Kelvin'),
 'L': ('http://unitsofmeasure.org', 'L', 'liter'),
 'Lf': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'Lf', None),
 'LfU/mL': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'LfU/mL', None),
 'Metric Ton': ('http://unitsofmeasure.org', 't', 'tonne'),
 'Mo': ('http://unitsofmeasure.org', 'mo', 'month'),
 'Monday': ('http://snomed.info/sct', '307145004', 'Monday'),
 'PFU': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'PFU', None),
 'PNU': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'PNU', None),
 'PNU/mL': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'PNU/mL', None),
 'Saturday': ('http://snomed.info/sct', '307151009', 'Saturday'),
 'Sunday': ('http://snomed.info/sct', '307146003', 'Sunday'),
 'T': ('http://unitsofmeasure.org', 'T', 'Tesla'),
 'TCID_50': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'TCID_50', None),
 'Thursday': ('http://snomed.info/sct', '307149005', 'Thursday'),
 'Ton': ('http://unitsofmeasure.org', '[ston_av]', 'short ton U.S. ton'),
 'Tuesday': ('http://snomed.info/sct', '307147007', 'Tuesday'),
 'U': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'U', None),
 "USP'U": ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', "USP'U", None),
 'Wednesday': ('http://snomed.info/sct', '307148002', 'Wednesday'),
 'X': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'X', None),
 'active': ('http://snomed.info/sct', '55561003', 'Active'),
 'after breakfast': ('http://ncimeta.nci.nih.gov', 'C1550743', None),
 'after dinner': ('http://ncimeta.nci.nih.gov', 'C1879671', None),
 'after exercise': ('http://snomed.info/sct', '255214003', 'Post exercise'),
 'after lunch': ('http://ncimeta.nci.nih.gov', 'C1879668', None),
 'after meal': ('http://snomed.info/sct', '24863003', 'pc - post cibum'),
 'afternoon': ('http://snomed.info/sct', '422133006', 'Afternoon'),
 'arteriovenous fistula': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'arteriovenous fistula', None),
 'arteriovenous graft': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'arteriovenous graft', None),
 'at rest': ('http://snomed.info/sct', '263678003', 'At rest'),
 'auricular': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'auricular', None),
 'bar': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'bar', None),
 'bead': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'bead', None),
 'beats/min': ('http://unitsofmeasure.org', '/min', 'per minute'),
 'before breakfast': ('http://ncimeta.nci.nih.gov', 'C1549040', None),
 'before dinner': ('http://ncimeta.nci.nih.gov', 'C1550742', None),
 'before exercise': ('http://snomed.info/sct', '307166007', 'Before exercise'),
 'before lunch': ('http://ncimeta.nci.nih.gov', 'C1550741', None),
 'before meal': ('http://snomed.info/sct', '307165006', 'Before meal'),
 'before sleeping': ('http://snomed.info/sct', '307155000', 'Before sleeping'),
 'body cavity': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'body cavity', None),
 'breaths/min': ('http://unitsofmeasure.org', '/min', 'per minute'),
 'buccal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'buccal', None),
 'cL': ('http://unitsofmeasure.org', 'cL', 'centiliter'),
 'capillary blood': ('http://snomed.info/sct', '122554006', 'Capillary blood sample'),
 'capsule': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'capsule', None),
 'caudal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'caudal', None),
 'cellular sheet': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'cellular sheet', None),
 'cloth': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'cloth', None),
 'cm': ('http://unitsofmeasure.org', 'cm', 'centimeter'),
 'cm^2': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'cm^2', None),
 'colostomy': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'colostomy', None),
 'conjunctival': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'conjunctival', None),
 'cutaneous': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'cutaneous', None),
 'd': ('http://unitsofmeasure.org', 'd', 'day'),
 'dL': ('http://unitsofmeasure.org', 'dL', 'deciliter'),
 'dental': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'dental', None),
 'digestive tract': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'digestive tract', None),
 'disc': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'disc', None),
 'douche': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'douche', None),
 'drop': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'drop', None),
 'during exercise': ('http://snomed.info/sct', '309604004', 'During exercise'),
 'during sleep': ('http://snomed.info/sct', '309610004', 'During sleep'),
 'electro-osmosis': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'electro-osmosis', None),
 'endocervical': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'endocervical', None),
 'endosinusial': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'endosinusial', None),
 'endotracheopulmonary': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'endotracheopulmonary', None),
 'enteral': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'enteral', None),
 'epidural': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'epidural', None),
 'episode': ('http://www.fhir.org/guides/mfhir/CodeSystem/descriptive-statistic-denominator', 'episode', None),
 'esophagostomy': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'esophagostomy', None),
 'evening': ('http://snomed.info/sct', '3157002', 'During the evening'),
 'extra-amniotic': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'extra-amniotic', None),
 'extracorporeal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'extracorporeal', None),
 'fL': ('http://unitsofmeasure.org', 'fL', 'femtoliter'),
 'fasting': ('http://snomed.info/sct', '16985007', 'Fasting'),
 'fg': ('http://unitsofmeasure.org', 'fg', 'femtogram'),
 'fistula': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'fistula', None),
 'fl oz': ('http://unitsofmeasure.org', '[foz_us]', 'fluid ounce'),
 'fm': ('http://unitsofmeasure.org', 'fm', 'femtometer'),
 'ft': ('http://unitsofmeasure.org', '[ft_i]', 'Feet'),
 'ft^2': ('http://unitsofmeasure.org', '[sft_i]', 'square foot (international)'),
 'g': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'g', None),
 'gal': ('http://unitsofmeasure.org', '[gal_us]', "Queen Anne's wine gallon"),
 'gastro-intestinal stoma': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'gastro-intestinal stoma', None),
 'gastroenteral': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'gastroenteral', None),
 'gastrostomy': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'gastrostomy', None),
 'gingival': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'gingival', None),
 'globule': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'globule', None),
 'gr': ('http://unitsofmeasure.org', 'gr', None),
 'granule': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'granule', None),
 'gum': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'gum', None),
 'h': ('http://unitsofmeasure.org', 'h', 'hour'),
 'hemodialysis': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'hemodialysis', None),
 'hp_C': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'hp_C', None),
 'hp_M': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'hp_M', None),
 'hp_Q': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'hp_Q', None),
 'hp_X': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'hp_X', None),
 'ileostomy': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'ileostomy', None),
 'in': ('http://unitsofmeasure.org', '[in_i]', 'inch (international)'),
 'in^2': ('http://unitsofmeasure.org', '[sin_i]', 'square inch (international)'),
 'in^3': ('http://unitsofmeasure.org', '[cin_i]', 'cubic inch'),
 'infiltration': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'infiltration', None),
 'interstitial': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'interstitial', None),
 'interstitial fluid': ('http://snomed.info/sct', '258479004', 'Interstitial fluid specimen'),
 'intra-abdominal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intra-abdominal', None),
 'intra-amniotic': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intra-amniotic', None),
 'intra-arterial': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intra-arterial', None),
 'intra-articular': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intra-articular', None),
 'intrabiliary': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intrabiliary', None),
 'intrabronchial': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intrabronchial', None),
 'intrabursal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intrabursal', None),
 'intracameral': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intracameral', None),
 'intracardiac': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intracardiac', None),
 'intracartilaginous': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intracartilaginous', None),
 'intracaudal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intracaudal', None),
 'intracavernous': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intracavernous', None),
 'intracavitary': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intracavitary', None),
 'intracerebral': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intracerebral', None),
 'intracerebroventricular': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intracerebroventricular', None),
 'intracisternal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intracisternal', None),
 'intracolonic': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intracolonic', None),
 'intracorneal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intracorneal', None),
 'intracoronal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intracoronal', None),
 'intracoronary': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intracoronary', None),
 'intracorporus cavernosum': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intracorporus cavernosum', None),
 'intracranial': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intracranial', None),
 'intradermal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intradermal', None),
 'intradiscal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intradiscal', None),
 'intraductal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraductal', None),
 'intraduodenal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraduodenal', None),
 'intradural': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intradural', None),
 'intraepicardial': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraepicardial', None),
 'intraepidermal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraepidermal', None),
 'intraesophageal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraesophageal', None),
 'intragastric': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intragastric', None),
 'intragingival': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intragingival', None),
 'intrahepatic': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intrahepatic', None),
 'intraileal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraileal', None),
 'intrajejunal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intrajejunal', None),
 'intralesional': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intralesional', None),
 'intralingual': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intralingual', None),
 'intraluminal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraluminal', None),
 'intralymphatic': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intralymphatic', None),
 'intramammary': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intramammary', None),
 'intramedullary': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intramedullary', None),
 'intrameningeal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intrameningeal', None),
 'intramural': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intramural', None),
 'intramuscular': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intramuscular', None),
 'intramyometrial': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intramyometrial', None),
 'intraneural': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraneural', None),
 'intranodal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intranodal', None),
 'intraocular': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraocular', None),
 'intraomentum': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraomentum', None),
 'intraosseous': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraosseous', None),
 'intraovarian': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraovarian', None),
 'intrapericardial': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intrapericardial', None),
 'intraperitoneal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraperitoneal', None),
 'intrapleural': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intrapleural', None),
 'intraprostatic': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraprostatic', None),
 'intrapulmonary': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intrapulmonary', None),
 'intraruminal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraruminal', None),
 'intrasinal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intrasinal', None),
 'intraspinal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraspinal', None),
 'intrasternal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intrasternal', None),
 'intrasynovial': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intrasynovial', None),
 'intratendinous': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intratendinous', None),
 'intratesticular': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intratesticular', None),
 'intrathecal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intrathecal', None),
 'intrathoracic': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intrathoracic', None),
 'intratubular': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intratubular', None),
 'intratumor': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intratumor', None),
 'intratympanic': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intratympanic', None),
 'intrauterine': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intrauterine', None),
 'intravascular': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intravascular', None),
 'intravenous': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intravenous', None),
 'intravenous central': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intravenous central', None),
 'intravenous peripheral': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intravenous peripheral', None),
 'intraventricular - cardiac': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intraventricular - cardiac', None),
 'intravesical': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intravesical', None),
 'intravitreal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'intravitreal', None),
 'iontophoresis': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'iontophoresis', None),
 'irrigation': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'irrigation', None),
 'jejunostomy': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'jejunostomy', None),
 'kL': ('http://unitsofmeasure.org', 'kL', 'kiloliter'),
 'kcal': ('http://unitsofmeasure.org', 'kCal', None),
 'kg': ('http://unitsofmeasure.org', 'kg', 'kilogram'),
 'kg/m^2': ('http://unitsofmeasure.org', 'kg/m2', 'kilogram / (meter ^ 2)'),
 'km': ('http://unitsofmeasure.org', 'km', 'kilometer'),
 'km/h': ('http://unitsofmeasure.org', 'km/h', 'kilometer / hour'),
 'km^2': ('http://unitsofmeasure.org', 'km2', '(kilometer ^ 2)'),
 'kp_C': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'kp_C', None),
 'laryngeal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'laryngeal', None),
 'lb': ('http://unitsofmeasure.org', '[lb_av]', 'pound (US and British)'),
 'left ankle': ('http://www.fhir.org/guides/mfhir/CodeSystem/body-location', 'left ankle', None),
 'left hip': ('http://www.fhir.org/guides/mfhir/CodeSystem/body-location', 'left hip', None),
 'left thigh': ('http://www.fhir.org/guides/mfhir/CodeSystem/body-location', 'left thigh', None),
 'left thorax': ('http://www.fhir.org/guides/mfhir/CodeSystem/body-location', 'left thorax', None),
 'left upper arm': ('http://www.fhir.org/guides/mfhir/CodeSystem/body-location', 'left upper arm', None),
 'left wrist': ('http://www.fhir.org/guides/mfhir/CodeSystem/body-location', 'left wrist', None),
 'lower respiratory tract': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'lower respiratory tract', None),
 'lozenge': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'lozenge', None),
 'lying down': ('http://snomed.info/sct', '102538003', 'Recumbent body position'),
 'm': ('http://unitsofmeasure.org', 'm', 'meter'),
 'm/s': ('http://unitsofmeasure.org', 'm/s', 'meter per second'),
 'mCi': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'mCi', None),
 'mCi/mL': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'mCi/mL', None),
 'mEq': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'mEq', None),
 'mL': ('http://unitsofmeasure.org', 'mL', 'milliliter'),
 'mT': ('http://unitsofmeasure.org', 'mT', 'millitesla'),
 'mU': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'mU', None),
 'm^2': ('http://unitsofmeasure.org', 'm2', 'square meter'),
 'meal': ('http://www.fhir.org/guides/mfhir/CodeSystem/descriptive-statistic-denominator', 'meal', None),
 'mg': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'mg', None),
 'mg/actuat': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'mg/actuat', None),
 'mg/dL': ('http://unitsofmeasure.org', 'mg/dL', 'milligram per deciliter'),
 'mg/hr': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'mg/hr', None),
 'mg/mL': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'mg/mL', None),
 'mg/mg': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'mg/mg', None),
 'mi': ('http://unitsofmeasure.org', '[mi_i]', 'statute mile'),
 'mi^2': ('http://unitsofmeasure.org', '[smi_i]', None),
 'middle left thorax': ('http://www.fhir.org/guides/mfhir/CodeSystem/body-location', 'middle left thorax', None),
 'min': ('http://unitsofmeasure.org', 'min', 'minute'),
 'min/km': ('http://unitsofmeasure.org', 'min/km', 'minute / kilometer'),
 'min/mi': ('http://unitsofmeasure.org', 'min/[mi_us]', 'minute / mile'),
 'mm': ('http://unitsofmeasure.org', 'mm', 'millimeter'),
 'mmHg': ('http://unitsofmeasure.org', 'mm[Hg]', 'millimeter of mercury'),
 'mm^2': ('http://unitsofmeasure.org', 'mm2', 'square millimeter'),
 'mmol': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'mmol', None),
 'mmol/L': ('http://unitsofmeasure.org', 'mmol/L', 'millimole per liter'),
 'mol': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'mol', None),
 'morning': ('http://snomed.info/sct', '73775008', 'Morning'),
 'ms': ('http://unitsofmeasure.org', 'ms', 'millisecond'),
 'mucous fistula': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'mucous fistula', None),
 'nL': ('http://unitsofmeasure.org', 'nL', 'nanoliter'),
 'nT': ('http://unitsofmeasure.org', 'nT', 'nanotesla'),
 'nasal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'nasal', None),
 'nasoduodenal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'nasoduodenal', None),
 'nasogastric': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'nasogastric', None),
 'nasojejunal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'nasojejunal', None),
 'ng': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'ng', None),
 'night': ('http://snomed.info/sct', '2546009', 'on - omni nocte'),
 'nm': ('http://unitsofmeasure.org', 'nm', 'nanometer'),
 'nmol': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'nmol', None),
 'not applicable': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'not applicable', None),
 'not fasting': ('http://snomed.info/sct', '440565004', 'Nonfasting'),
 'ns': ('http://unitsofmeasure.org', 'ns', 'nanosecond'),
 'occlusive dressing technique': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'occlusive dressing technique', None),
 'on waking': ('http://snomed.info/sct', '307156004', 'On waking'),
 'ophthalmic': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'ophthalmic', None),
 'oral': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'oral', None),
 'organisms': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'organisms', None),
 'orogastric': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'orogastric', None),
 'oromucosal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'oromucosal', None),
 'oropharyngeal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'oropharyngeal', None),
 'otic': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'otic', None),
 'oz': ('http://unitsofmeasure.org', '[oz_av]', 'ounce (US and British)'),
 'pL': ('http://unitsofmeasure.org', 'pL', 'picoliter'),
 'pT': ('http://unitsofmeasure.org', 'pT', 'picotesla'),
 'paracervical': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'paracervical', None),
 'paravertebral': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'paravertebral', None),
 'parenteral': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'parenteral', None),
 'pastille': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'pastille', None),
 'patch': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'patch', None),
 'pellet': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'pellet', None),
 'percutaneous': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'percutaneous', None),
 'periarticular': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'periarticular', None),
 'peribulbar': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'peribulbar', None),
 'peridural': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'peridural', None),
 'perineural': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'perineural', None),
 'periodontal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'periodontal', None),
 'periosteal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'periosteal', None),
 'peritendinous': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'peritendinous', None),
 'periurethral': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'periurethral', None),
 'pg': ('http://unitsofmeasure.org', 'pg', 'picogram'),
 'pill': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'pill', None),
 'plasma': ('http://snomed.info/sct', '119361006', 'Plasma sample'),
 'pm': ('http://unitsofmeasure.org', 'pm', 'picometer'),
 'pouch': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'pouch', None),
 'ps': ('http://unitsofmeasure.org', 'ps', 'picosecond'),
 'pt': ('http://unitsofmeasure.org', '[pt_us]', 'pint'),
 'puff': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'puff', None),
 'qt': ('http://unitsofmeasure.org', '[qt_us]', 'quart'),
 'rectal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'rectal', None),
 'respiratory tract': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'respiratory tract', None),
 'retrobulbar': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'retrobulbar', None),
 'right ankle': ('http://www.fhir.org/guides/mfhir/CodeSystem/body-location', 'right ankle', None),
 'right hip': ('http://www.fhir.org/guides/mfhir/CodeSystem/body-location', 'right hip', None),
 'right thigh': ('http://www.fhir.org/guides/mfhir/CodeSystem/body-location', 'right thigh', None),
 'right upper arm': ('http://www.fhir.org/guides/mfhir/CodeSystem/body-location', 'right upper arm', None),
 'right wrist': ('http://www.fhir.org/guides/mfhir/CodeSystem/body-location', 'right wrist', None),
 'ring': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'ring', None),
 'salve': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'salve', None),
 'sec': ('http://unitsofmeasure.org', 'sec', None),
 'semi-recumbent': ('http://snomed.info/sct', '272580008', 'Semi-recumbent position'),
 'serum': ('http://snomed.info/sct', '119364003', 'Serum sample'),
 'session': ('http://www.fhir.org/guides/mfhir/CodeSystem/descriptive-statistic-denominator', 'session', None),
 'sitting': ('http://snomed.info/sct', '33586001', 'Sitting position'),
 'soft tissue': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'soft tissue', None),
 'standing': ('http://snomed.info/sct', '10904000', 'Orthostatic body position'),
 'steps': ('http://unitsofmeasure.org', '{steps}', '"steps"'),
 'stick': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'stick', None),
 'strip': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'strip', None),
 'subarachnoid': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'subarachnoid', None),
 'subconjunctival': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'subconjunctival', None),
 'subcutaneous': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'subcutaneous', None),
 'subgingival': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'subgingival', None),
 'sublesional': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'sublesional', None),
 'sublingual': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'sublingual', None),
 'submucosal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'submucosal', None),
 'suborbital': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'suborbital', None),
 'subretinal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'subretinal', None),
 'subtendinous': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'subtendinous', None),
 'suppository': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'suppository', None),
 'surgical cavity': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'surgical cavity', None),
 'surgical drain': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'surgical drain', None),
 'swab': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'swab', None),
 'tablet': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'tablet', None),
 'tampon': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'tampon', None),
 'tape': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'tape', None),
 'tbsp': ('http://unitsofmeasure.org', '[tbs_us]', 'tablespoon (US)'),
 'tears': ('http://snomed.info/sct', '122594008', 'Tears specimen'),
 'topical': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'topical', None),
 'transcervical': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'transcervical', None),
 'transdermal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'transdermal', None),
 'transendocardial': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'transendocardial', None),
 'transmucosal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'transmucosal', None),
 'transplacental': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'transplacental', None),
 'transtracheal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'transtracheal', None),
 'transtympanic': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'transtympanic', None),
 'transurethral': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'transurethral', None),
 'tsp': ('http://unitsofmeasure.org', '[tsp_us]', 'teaspoon'),
 'tumor cavity': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'tumor cavity', None),
 'uCi': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'uCi', None),
 'uL': ('http://unitsofmeasure.org', 'uL', 'microliter'),
 'uT': ('http://unitsofmeasure.org', 'uT', 'microtesla'),
 'ug': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'ug', None),
 'ug/mL': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'ug/mL', None),
 'um': ('http://unitsofmeasure.org', 'um', 'micrometer'),
 'umol': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'umol', None),
 'unt': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'unt', None),
 'unt/mL': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'unt/mL', None),
 'ureteral': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'ureteral', None),
 'urethral': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'urethral', None),
 'urostomy': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'urostomy', None),
 'us': ('http://unitsofmeasure.org', 'us', 'microsecond'),
 'vaginal': ('http://www.fhir.org/guides/mfhir/CodeSystem/intervention-administration-route', 'vaginal', None),
 'vial': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'vial', None),
 'wafer': ('http://www.fhir.org/guides/mfhir/CodeSystem/medication-dose-unit', 'wafer', None),
 'whole blood': ('http://snomed.info/sct', '258580003', 'Whole blood sample'),
 'with food': ('http://snomed.info/sct', '311504000', 'With or after food'),
 'with meal': ('http://snomed.info/sct', '311503006', 'With or after meal'),
 'wk': ('http://unitsofmeasure.org', 'wk', 'week'),
 'yd': ('http://unitsofmeasure.org', '[yd_i]', 'yard'),
 'yd^2': ('http://unitsofmeasure.org', '[syd_i]', 'square yard'),
 'yr': ('http://unitsofmeasure.org', 'a', 'year')
 }